### ISSUE TITLE
Fence Objekts can´t recolor correct

### ISSUE THREAD

**Issue by Ranchuu** [Parkitect/ParkitectAssetEditor#1]
When i try to build fence objekts, they cant recolored ingame. There is just the standard red color on it. If i use the same objekt as a deco objekt, it works fine.

**Comment by luukholleman** [comment]
I'll check it out tomorrow

**Comment by luukholleman** [comment]
I've found and fixed the issue. The bug was located in Parkitect which means it'll work with the next game update.
